#!/bin/bash
cat /dev/stdin | head  -n -1 | sed  '0,/Labels/d' | tail -n +2 > program/temp.p1
echo Original Program
echo --------------
cd program
cat temp.p1
#sed -i 's/%r[[:digit:]]/ 1&d/g' temp.p1
sed -i 's/%r0/ %r0 /g' temp.p1
sed -i 's/%r1/ %r1 /g' temp.p1
sed -i 's/%r2/ %r2 /g' temp.p1
sed -i 's/%r3/ %r3 /g' temp.p1
sed -i 's/%r4/ %r4 /g' temp.p1
sed -i 's/%r5/ %r5 /g' temp.p1

sed -i 's/ %r0 /%r10d/g' temp.p1
sed -i 's/ %r1 /%r11d/g' temp.p1
sed -i 's/ %r2 /%r12d/g' temp.p1
sed -i 's/ %r3 /%r13d/g' temp.p1
sed -i 's/ %r4 /%r14d/g' temp.p1
sed -i 's/ %r5 /%r15d/g' temp.p1
sed -i 's/,%/, %/g' temp.p1
echo Extracted Program
echo ------------------
cat temp.p1
cd ..
