#!/bin/bash
cat /dev/stdin | head  -n -1 | sed  '0,/Labels/d' | tail -n +2 > program/temp.cara
#sed -i 's/%r[[:digit:]]/ 1&d/g' temp.cara
cd program	
sed -i 's/%r0/ %r0 /g' temp.cara
sed -i 's/%r1/ %r1 /g' temp.cara
sed -i 's/%r2/ %r2 /g' temp.cara
sed -i 's/%r3/ %r3 /g' temp.cara
sed -i 's/%r4/ %r4 /g' temp.cara
sed -i 's/%r5/ %r5 /g' temp.cara

sed -i 's/ %r0 /%r10d/g' temp.cara
sed -i 's/ %r1 /%r11d/g' temp.cara
sed -i 's/ %r2 /%r12d/g' temp.cara
sed -i 's/ %r3 /%r13d/g' temp.cara
sed -i 's/ %r4 /%r14d/g' temp.cara
sed -i 's/ %r5 /%r15d/g' temp.cara
sed -i 's/,%/, %/g' temp.cara
cat temp.cara
cd ..
