#!/bin/bash

./build.sh tests/$1 > program/debug.p1
./build.sh tests/$1 | ./extractProgram > program/temp.p1
cd program
cp temp.p1 provolone.s
gcc -no-pie -o prog.out main.c provolone.s && ./prog.out
cd ..
